"""Initial migration

Revision ID: 0cba16788431
Revises: 
Create Date: 2025-03-31 21:51:18.747764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cba16788431'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('platform_url', sa.String(), nullable=False),
    sa.Column('author_username', sa.String(), nullable=True),
    sa.Column('author_platform_id', sa.String(), nullable=True),
    sa.Column('author_avatar_url', sa.String(), nullable=True),
    sa.Column('content_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimenttype'), nullable=True),
    sa.Column('category', sa.Enum('BUG', 'FEATURE_REQUEST', 'QUESTION', 'PRAISE', 'COMPLAINT', name='categorytype'), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'VIEWED', 'RESPONDED', name='poststatus'), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ### 